services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django.
      POSTGRES_DB: django
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
  api_server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - postgres
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./tutorial:/code/
    command: "python manage.py runserver 0.0.0.0:8000"
volumes:
  pgdata:
networks:
  backend:
    driver: bridge