version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
  api_server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - postgres
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./tutorial:/code/
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: "python manage.py runserver 0.0.0.0:8000"
volumes:
  pgdata:
networks:
  backend:
    driver: bridge